### ISSUE TITLE
Unknown command: "sm_taunt_list"

### ISSUE THREAD

**Issue by gabsF** [fakuivan/TF2-Taunts-TF2IDB#32] opened 2019-01-05 02:59 UTC
so, i've installed all the requirements for the taunts plugin, i double-checked everything, but for some reason, its always giving `unknown command: "sm_taunt_list"`

and when i put the command: `sm plugins load tf2_taunts_tf2idb`
it says `Plugin tf2_taunts_tf2idb.smx is already loaded.`
but, when i execute the command `sm_taunt_list`
it appears `unknown command: "sm_taunt_list"`

anyway, i'll go to sleep and i'll answer ASAP, well, if you answer me

**Comment by fakuivan** [comment] 2019-01-06 15:49
Check the logs as always, there should be info about the error there. This plugin will not unload by design, in case the updater wants to update it. The user interface will only register to sourcemod if the variable ``gi_initialization`` is set to ``InitializationStatus_Success``. 

https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/00bac1b8aa43e140ba1f12d7756b98df5a7989bd/scripting/tf2_taunts_tf2idb.sp#L117-L128

**Comment by gabsF** [comment] 2019-01-06 20:39
hm, seems that tf2idb is the error
```
[SM] Exception reported: no such table: tf2idb_item
[SM] Blaming: tf2idb.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 66, tf2idb.sp::OnPluginStart
[SM] Unable to load plugin "tf2idb.smx": Error detected in plugin startup (see error logs)
[tf2_taunts_tf2idb.smx] Failed to initialize taunt cache: TF2IDB Not loaded.
[tf2_taunts_tf2idb.smx] Halting user interface initialization. Plugin loaded, waiting for updates.
```

**Comment by fakuivan** [comment] 2019-01-07 00:37
Try to fix your problem and close this if everything works.

**Closed as completed** 2019-01-10 16:50 UTC
